server {
    listen 80;
    server_name presence.inytel.com;
    return 301 https://$host:8443$request_uri;
}

server {
    listen 80 default_server;
    server_name localhost 127.0.0.1 _;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        proxy_pass http://inytel-api-v2:3001;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}

server {
    listen 8443 ssl;
    server_name presence.inytel.com;
    ssl_certificate     /etc/letsencrypt/live/presence.inytel.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/presence.inytel.com/privkey.pem;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        proxy_pass http://inytel-api-v2:3001;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}